name: gui-snap-demo # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: GLMark2 on wayland # 79 char long summary
description: |
  GLMark2 on Wayland

confinement: strict # use 'strict' once you have the right plugs and slots
grade: devel

apps:
  glmark2-wayland:
    command: "bash -c 'XDG_RUNTIME_DIR=$SNAP_DATA/wayland LIBGL_DRIVERS_PATH=$(find $SNAP/usr/lib/ -name dri) $SNAP/usr/bin/glmark2-wayland'"
    plugs:
      - opengl
      - wayland

parts:
  glmark2-wayland:
    # See 'snapcraft plugins'
    plugin: nil
    stage-packages:
      - glmark2-wayland

passthrough:
  layout:
    /usr/share/glmark2:
      bind: $SNAP/usr/share/glmark2

plugs:
  wayland-socket-dir:
    content: wayland-socket-dir
    interface: content
    target: $SNAP_DATA/wayland
    default-provider: mir-kiosk